<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T90_groups_menu_model extends CI_Model
{

    public $table = 't90_groups_menu';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all where idgroups = $id
    function getAllByIdGroups($id)
    {
        $this->db->order_by('idmenu', 'asc');
        $this->db->where('idgroups', $id);
        $this->db->select($this->table.'.*');
        $this->db->select('groups.description');
        $this->db->select('menu.nama');
        $this->db->from($this->table);
        $this->db->join('t86_groups groups', 'groups.id = ' . $this->table . '.idgroups');
        $this->db->join('t89_menu menu', 'menu.id = ' . $this->table . '.idmenu');
        return $this->db->get()->result();
    }

    // datatables
    function json() {
        $this->datatables->select('id,idgroups,idmenu,rights');
        $this->datatables->from('t90_groups_menu');
		if (isset($_POST['id']) && $_POST['id'] != '') { $this->datatables->like('id', $_POST['id']); }
		if (isset($_POST['idgroups']) && $_POST['idgroups'] != '') { $this->datatables->like('idgroups', $_POST['idgroups']); }
		if (isset($_POST['idmenu']) && $_POST['idmenu'] != '') { $this->datatables->like('idmenu', $_POST['idmenu']); }
		if (isset($_POST['rights']) && $_POST['rights'] != '') { $this->datatables->like('rights', $_POST['rights']); }
        //add this line for join
        //$this->datatables->join('table2', 't90_groups_menu.field = table2.field');
        //$this->datatables->add_column('action', anchor(site_url('t90_groups_menu/update/$1'),'Ubah')." | ".anchor(site_url('t90_groups_menu/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'id');
        $action = "";
        $hakAkses = $this->session->userdata('hakAkses'.substr($this->uri->segment(1), 4));
        if ($hakAkses['ubah']) {
            $action = anchor(site_url('t90_groups_menu/update/$1'),'Ubah');
            if ($hakAkses['hapus']) {
                $action .= " | ";
            }
        }
        if ($hakAkses['hapus']) {
            $action .= anchor(site_url('t90_groups_menu/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"');
        }
        $this->datatables->add_column('action', $action, 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
		$this->db->or_like('idgroups', $q);
		$this->db->or_like('idmenu', $q);
		$this->db->or_like('rights', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
		$this->db->or_like('idgroups', $q);
		$this->db->or_like('idmenu', $q);
		$this->db->or_like('rights', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T90_groups_menu_model.php */
/* Location: ./application/models/T90_groups_menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-09-30 11:17:05 */
/* http://harviacode.com */
